export const CHANGE_MIDDLE_TILE_DATE = 'CHANGE_MIDDLE_TILE_DATE';
export const CHANGE_ACTIVE_TILE = 'CHANGE_ACTIVE_TILE';
export const SHOW_LOADER = 'SHOW_LOADER';
export const MOUNT_TILES = 'MOUNT_TILES';
export const GET_GAMES_FOR_TILES = 'GET_GAMES_FOR_TILES';
export const GET_GAMES_FOR_CALENDAR = 'GET_GAMES_FOR_CALENDAR';
